# Generated by Django 4.2.1 on 2025-02-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_apply_job_experience_alter_postjob_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('responsibilities', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
